---
output:
  pdf_document: default
urlcolor: blue
header-includes:    
  - \usepackage{lastpage}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead[CO, CE]{Hairuo Wang, 1004015932}
  - \fancyfoot[CO, CE]{\thepage \ of \pageref{LastPage}}
---

```{r setup, message = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk.

# These are the packages you will need for this activity
packages_needed <- c("tidyverse", "googledrive", "readxl", "janitor", 
                     "lubridate", "opendatatoronto", "ggthemes")

package.check <- lapply(
  packages_needed,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
    }
  }
)

# Credit: package.check based on a helpful post from Vikram Baliga https://vbaliga.github.io/verify-that-r-packages-are-installed-and-loaded/

# Load tidyverse
library(tidyverse)
library(readxl)
library(janitor)
library(opendatatoronto)
library(ggthemes)

# Set so that long lines in R will be wrapped:
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), echo = TRUE)
```


```{r getdata, eval = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk BUT...

# This chunk loads the most recent data from Toronto City and the data from OpenToronto.

# You have to RUN this chunk by hand to update the data as 
#   eval is set to FALSE to limit unnecessary requsts on the site.

###################################################
# Step one: Get the COVID data from Toronto City. #
###################################################

#googledrive::drive_deauth()

#url1 <- "https://drive.google.com/file/d/11KF1DuN5tntugNc10ogQDzFnW05ruzLH/view"
#googledrive::drive_download(url1, path="data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx", overwrite = TRUE)

#url2 <- "https://drive.google.com/file/d/1jzH64LvFQ-UsDibXO0MOtvjbL2CvnV3N/view"
#googledrive::drive_download(url2, path = "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx", overwrite = TRUE)

# this removes the url object that we don't need anymore
#rm(url1, url2)

#####################################################################
# Step two: Get the data neighbourhood data from Open Data Toronto. #
#####################################################################

nbhoods_shape_raw <- list_package_resources("neighbourhoods") %>% 
  get_resource()

saveRDS(nbhoods_shape_raw, "data/neighbourhood_shapefile.Rds")

nbhood_profile <- search_packages("Neighbourhood Profile") %>%
  list_package_resources() %>% 
  filter(name == "neighbourhood-profiles-2016-csv") %>% 
  get_resource()

saveRDS(nbhood_profile, "data/neighbourhood_profile.Rds")
```


```{r load_data, echo=FALSE}
######################################################
# Step three: Load the COVID data from Toronto City. #
######################################################

# Saving the name of the file as an object and then using the object name in the
# following code is a helpful practice. Why? If we change the name of the file 
# being used, we'll only have to change it in one place. This helps us avoid 
# 'human error'.

daily_data <- "data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx"

# Cases reported by date
reported_raw <- read_excel(daily_data, sheet = 5) %>% 
  clean_names()

# Cases by outbreak type
outbreak_raw <- read_excel(daily_data, sheet = 3) %>% 
  clean_names()

# When was this data updated?
date_daily <- read_excel(daily_data, sheet = 1) %>% 
  clean_names()

# By neighbourhood
neighbourood_data <- "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx"

# Cases reported by date
nbhood_raw <- read_excel(neighbourood_data, sheet = 2) %>% 
  clean_names()

# Date the neighbourhood data was last updated
date_nbhood <- read_excel(neighbourood_data, sheet = 1) %>% 
  clean_names()

#don't need these anymore
rm(daily_data, neighbourood_data)

#############################################################
# Step four: Load the neighbourhood data from Toronto City. #
#############################################################

# Get neighbourhood profile data
nbhood_profile <- readRDS("data/neighbourhood_profile.Rds")

# Get shape data for mapping 
nbhoods_shape_raw <- readRDS("data/neighbourhood_shapefile.Rds") %>% 
  sf::st_as_sf() ## Makes sure shape info is in the most up to date format

```

Code last run `r Sys.Date()`.  
Daily: `r date_daily[1,1]`.   
Neighbourhood: `r date_nbhood[1,1]`. 

# Task 1: Daily cases
## Data wrangling

```{r cases_dw}
#create new dataset reported and start with reported_raw
reported = reported_raw %>%
  #replace all NA values with 0
  mutate_if(is.numeric, replace_na, replace=0) %>%
  #overwrite reported_date with date version
  mutate(reported_date=date(reported_date)) %>% 
  #the data is not tidy, so alter it to be tidy. 
  pivot_longer(c(recovered, active, deceased), names_to = "Status", 
               values_to="Number_of_Cases") %>% 
  #capitalized
  mutate(Status = str_to_sentence(Status)) %>%
  #reorder the status and they could appear in correct order in the legend
  mutate(Status = fct_relevel(Status, "Deceased", after=2))
```

\newpage
## Data visualization

```{r cases_vis, warning=FALSE}
#visualize reported dataset
reported %>% 
  #Make x-axis, y-axis and fill
  ggplot(aes(x=reported_date, y=Number_of_Cases, fill = Status)) +
  #bar plot
  geom_bar(stat="identity")+
  #use minimal theme of the figure
  theme_minimal()+
  #add title, subtitle, number of x-axis, y-axis and caption of the figure
  labs(title = "Cases reported by day in Toronto, Canada", 
       subtitle = "Confirmed and probable cases", 
       x= "Date", 
       y= "Case count", 
       caption = str_c("Create by: Hairuo Wang for STA303/1002, U of T\n",
                       "Source: Ontario Ministry of Health, Integrated Public", 
                       " Health Information System and CORES\n", 
                       date_daily[1, 1])) +
  #set the limit and format of date on x-axis
  scale_x_date(labels = scales::date_format("%d %b %y"), 
               limits =c(date("2020-01-01"), Sys.Date()))+
  #legend without title and set the position
  theme(legend.title = element_blank(), legend.position = c(0.15, 0.75))+
  #set the color of fill
  scale_fill_manual(values = c("#003F5C", "#86BCB6", "#B9CA5D"))+
  #set the limit of value on y-axis
  scale_y_continuous(limits = c(0, 2000))
```

\newpage
# Task 2: Outbreak type
## Data wrangling

```{r outbreak_dw}
#create new dataset outbreak and start with outbreak_raw
outbreak = outbreak_raw %>% 
  #overwrite episode_week with date version
  mutate(episode_week=date(episode_week)) %>%
  #replace the name in order to get the same result with the given figure
  mutate(outbreak_or_sporadic = str_replace_all(outbreak_or_sporadic, "OB", 
                                                "outbreak")) %>%
  #capitalized word in order to get the same result with the given figure
  mutate(outbreak_or_sporadic = str_to_sentence(outbreak_or_sporadic)) %>% 
  #reorder the values
  mutate(outbreak_or_sporadic = fct_rev(outbreak_or_sporadic)) %>% 
  #create a new variable which is number of cases in episode week
  group_by(episode_week) %>% 
  mutate(total_case = sum(cases))
```

\newpage
## Data visualization

```{r outbreak_vis, warning=FALSE}
#visualize outbreak dataset
outbreak %>% 
  #make x-axis, y-axis and fill
  ggplot(aes(x=episode_week, y=cases, fill = outbreak_or_sporadic)) +
  #bar plot
  geom_bar(stat="identity") +
  #minimal theme
  theme_minimal()+
  #add title, subtitle, number of x-axis, y-axis and caption
  labs(title = "Cases by outbreak type and week in Toronto, Canada", 
       subtitle = "Confirmed and probable cases", 
       x = "Date", 
       y = "Case count", 
       caption = str_c("Create by: Hairuo Wang for STA303/1002, U of T\n",
                       "Source: Ontario Ministry of Health, Integrated Public", 
                       " Health Information System and CORES\n", 
                       date_daily[1, 1]))+
  #set limit and format of date on x-axis
  scale_x_date(labels = scales::date_format("%d %b %y"),
               limits = c(date("2020-01-01"), Sys.Date()+7))+
  #set limit f value on y-axis
  scale_y_continuous(limits=c(0, max(outbreak$total_case)))+
  #legend with no title and set position of legend
  theme(legend.title=element_blank(), legend.position=c(.15, .8))+
  #set color of fills
  scale_fill_manual(values=c("#86BCB6", "#B9CA5D"))
```

\newpage
# Task 3: Neighbourhoods
## Data wrangling: part 1

```{r nbhood_dw_1}
#create new dataset income and start with variable nbhood_profile
income = nbhood_profile %>% 
  #choose the row with id 1143 since it is relevant
  filter(`_id` == 1143) %>% 
  #The data is not tidy thus alter it to be tidy
  pivot_longer(-c(`_id`, Category, Topic, `Data Source`, Characteristic), 
               names_to = "neighbourhood_name", values_to = "low_income_percentage") %>%
  #convert percentage from character strings to numbers
  mutate(low_income_percentage=parse_number(low_income_percentage)) %>% 
  #since the neighbourhood name is not same in two dataset, so need to make it same. 
  mutate(neighbourhood_name = str_replace(neighbourhood_name, "Pelham", "Pellam")) %>% 
  mutate(neighbourhood_name = str_replace(neighbourhood_name, ". J", ".J"))
```

## Data wrangling: part 2

```{r nbhood_dw_2}
#create a new dataset nbhood_raw_new since we need to ensure the neighbourhood are correctly matched
#thus we want to change some element in dataset nbhood_raw
nbhood_raw_new = nbhood_raw %>%
  #remove the useless and not matched column
  filter(neighbourhood_name != "Missing Address/Postal Code") %>% 
  #make the neighbourhood name same
  mutate(neighbourhood_name = str_replace(neighbourhood_name, "Pelham", "Pellam")) %>% 
  mutate(neighbourhood_name = str_replace(neighbourhood_name, ". J", ".J"))
#create a new dataset nbhoods_all and start with dataset nbhoods_shape_new
nbhoods_all= nbhoods_shape_raw %>% 
  #remove space and number in parentheses in AREA_NAME variable
  #and save them into new variable
  mutate(neighbourhood_name = str_remove(AREA_NAME, "\\s\\(\\d+\\)$")) %>% 
  #merge income so we have low income percentages
  left_join(income, by = "neighbourhood_name") %>% 
  #merge nvhood_raw_new so we have case per 100000 people and case rate
  left_join(nbhood_raw_new, by = "neighbourhood_name") %>% 
  #rename the case rate variable
  rename(rate_per_100000 = rate_per_100_000_people)
```

## Data wrangling: part 3

```{r nbhood_dw_3}
#create a new dataset and start with dataset nbhoods_all
nbhoods_final = nbhoods_all %>%
  #create a new variable med_inc and get the median of low_income_percentage overall
  mutate(med_inc = median(low_income_percentage)) %>% 
  #create a new variable med_rate and get the median of case rate overall
  mutate(med_rate = median(rate_per_100000)) %>% 
  #create a new variable nbhood_type and classify the type of cases
  mutate(nbhood_type = case_when(
    low_income_percentage >= med_inc&rate_per_100000 >= med_rate ~ 
      "Higher low income rate, higher case rate", 
    low_income_percentage >= med_inc&rate_per_100000 < med_rate ~ 
      "Higher low income rate, lower case rate", 
    low_income_percentage < med_inc&rate_per_100000 >= med_rate ~ 
      "Lower low income rate, higher case rate", 
    low_income_percentage < med_inc&rate_per_100000 < med_rate ~ 
      "Lower low income rate,lower case rate"
  ))
```

\newpage
## Data visualization

```{r neighbourhood_graphs_1, warning=FALSE, fig.height=4}
#visualize percentage low income within map
ggplot(data=nbhoods_final) +
  #set fills
  geom_sf(aes(fill = low_income_percentage))+
  #create map
  theme_map()+
  #add title, subtitle and caption of the figure
  labs(title = "Percentage of 18 to 64 year olds living in a low income family (2015)", 
       subtitle = "Neighbourhoods of Toronto, Canada", 
       caption = str_c("Created by: Hairuo Wang for STA303/1002, U of T\n", 
                       "Sources: Census Profile 98-316-X2016001 via OpenData Toronto\n", 
                       date_daily[1, 1]))+
  #set name of legend and color of degree
  scale_fill_gradient(name="% low income", low= "darkgreen", high="lightgrey")+
  #set the position of the legend
  theme(legend.position="right")
```

\newpage

```{r neighbourhood_graphs_2, warning=FALSE, fig.height=4}
#visualize case rate within map 
ggplot(data=nbhoods_final) +
  #set fills
  geom_sf(aes(fill = rate_per_100000))+
  #create map
  theme_map()+
  #add title and caption of the figure
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada", 
       caption = str_c("Created by: Hairuo Wang for STA303/1002, U of T\n", 
                       "Source: Ontario Ministry of Health, Integrated Public Health",
                       " Information System and CORES\n",
                       date_daily[1, 1]))+
  #set name of legend and color of degree
  scale_fill_gradient(name="Cases per 100,000 people", low= "white", high="darkorange")+
  #set position of legend
  theme(legend.position="right")
```

\newpage

```{r neighbourhood_graphs_3, warning=FALSE, fig.height=4}
#visualize type of case and low income within map
ggplot(data=nbhoods_final) +
  #set fill
  geom_sf(aes(fill = nbhood_type))+
  #create map
  theme_map()+
  #add title and caption
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada", 
       caption = str_c("Created by: Hairuo Wang for STA303/1002, U of T\n", 
                       "Income data source: Census Profile 98-316-X2016001 via OpenData", 
                       " Toronto\n",
                       "COVID data source: Ontario Ministry of Health, Integrated Public\n", 
                       "Health Information System and CORES\n",
                       date_daily[1, 1]))+
  #set title of legend and color of each type
  scale_fill_brewer(palette = "Set1", name=str_c("% of 18 to 64 year-olds in\n", 
                                                 "low income families and\n", 
                                                 "COVID-19 case rates"))+
  #set position of legend
  theme(legend.position="right")
```




```{r, eval = FALSE, echo=FALSE}
# This chunk of code helps you prepare your assessment for submission on Crowdmark
# This is optional. If it isn't working, you can do it manually/take another approach.

# Run this chunk by hand after knitting your final version of your pdf for submission.
# A new file called 'to_submit' will appear in your working directory with each page of your assignment as a separate pdf.

# Install the required packages
if(!match("staplr", installed.packages()[,1], nomatch = FALSE))
  {install.packages("staplr")}

# Don't edit anything in this function
prep_for_crowdmark <- function(pdf=NULL){
  # Get the name of the file you're currently in. 
  this_file <- rstudioapi::getSourceEditorContext()$path
  pdf_name <- sub(".Rmd", ".pdf", sub('.*/', '', this_file))
  
  # Create a file called to_submit to put the individual files in
  # This will be in the same folder as this file is saved
  if(!match("to_submit", list.files(), nomatch = FALSE))
    {dir.create("to_submit")}
 
  # Split the files
  if(is.null(pdf)){
  staplr::split_pdf(pdf_name, output_directory = "to_submit", prefix = "page_")} else {
    staplr::split_pdf(pdf, output_directory = "to_submit", prefix = "page_") 
  }
}

prep_for_crowdmark()

```